Prevent execution of suid/sgid programs by torsocks
We already do this in usewithtor. Closes off
http://code.google.com/p/torsocks/issues/detail?id=5

diff --git a/src/torsocks.in b/src/torsocks.in
--- a/src/torsocks.in
+++ b/src/torsocks.in
@@ -63,6 +63,11 @@
 # Tamas Szerb <toma@rulez.org>
 # Modified by Robert Hogan <robert@roberthogan.net> April 16th 2006
 
+set_id () {
+    echo "ERROR: $1 is set${2}id. torsocks will not work on a set${2}id executable." >&2
+    exit 1
+}
+
 if [ $# = 0 ] ; then
    echo "$0: insufficient arguments"
    exit
@@ -122,6 +127,11 @@ case "$1" in
 
     if [ $# -gt 0 ]
     then
+      if [ -u `which "$1"` ]; then
+          set_id $1 u
+      elif [ -g `which "$1"` ]; then
+          set_id $1 g
+      fi
       exec "$@"
     fi
   ;;
