Clarify use of the configuration file.
Amend the default behaviour to work as summarized below and updated the
manual pages to make the default behaviour obvious to users.

"By default, torsocks will assume that it should connect to the SOCKS proxy
running at 127.0.0.1 on port 9050. This is the default address and port for
Tor's socks server on most installations.

In order to use a configuration file, you must set the environment variable
TORSOCKS_CONF_FILE with the location of the file.

If TORSOCKS_CONF_FILE is not set, torsocks will attempt to read the configuration
file at @CONFDIR@/torsocks.conf. If that file cannot be read, torsocks will
use sensible defaults for most Tor installations, i.e. it will assume that
you want to use a SOCKS proxy running at 127.0.0.1 (localhost) on port 9050."

diff --git a/src/usewithtor.in b/src/usewithtor.in
--- a/src/usewithtor.in
+++ b/src/usewithtor.in
@@ -92,14 +92,14 @@ fi
 
 if [ "$PROG" = "torsocks" ]; then
 	# Define our torsocks config file
-	TSOCKS_CONF_FILE="@CONFDIR@/torsocks.conf"
-	export TSOCKS_CONF_FILE
+	TORSOCKS_CONF_FILE="@CONFDIR@/torsocks.conf"
+	export TORSOCKS_CONF_FILE
 
 	# Check that we've got a torsocks config file
-	if [ -r "$TSOCKS_CONF_FILE" ]; 	then
+	if [ -r "$TORSOCKS_CONF_FILE" ]; 	then
 		exec torsocks "$@"
 	else
-		echo "$0: Missing torsocks configuration file \"$TSOCKS_CONF_FILE\" - torsocks will use defaults sensible for Tor." >&2
+		echo "$0: Missing torsocks configuration file \"$TORSOCKS_CONF_FILE\" - torsocks will use defaults sensible for Tor." >&2
 		exec torsocks "$@"
 	fi
 fi
